### ISSUE TITLE
License for code is missing - especially for network analysis (Kumu)

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/environment-and-sustainability-gc-community#3]
### Summary Sentence

Can we add the MIT license to the current License doc?
Example: https://github.com/the-turing-way/reproducible-project-template/blob/main/LICENSE.md

### What needs to be done?

Agree on a license for code to allow reuse.

### Who can help?

Cass, Alejandro

---

### Update after the issue was opened

[Add details]

**Comment by cassgvp** [comment]
Thank you for catching this, @malvikasharan ! Now added the MIT license for code, templating from [TTW LICENSE.md](https://github.com/the-turing-way/the-turing-way/blob/main/LICENSE.md), with acknoledgement :).
